ktor:
  application:
    modules:
      - com.passman.ApplicationKt.module
  deployment:
    port: 80
db:
  jdbcUrl: "jdbc:postgresql://localhost:5432/Passman"
  driverClassName: "org.postgresql.Driver"
  username: "admin"
  password: "example"